name: Extract and upload translations, create PR

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  Extract-Translations-to-upload-Simplelocalize:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
        with:
          token: ${{ secrets.GITHUB }}
          repository: taichi-t/blog_v2
      - uses: actions/setup-node@v1
        with:
          node-version: '12'
      - name: Install SimpleLocalize CLI
        run: curl -s https://get.simplelocalize.io/install | bash
      - name: Extract Translation File
        run: npx --package @formatjs/cli formatjs extract "(components|pages|hooks)/**/*.ts*" --out-file=./lang/en-US.json --id-interpolation-pattern='[sha512:contenthash:base64:6]' --format simple
      - name: Upload the Translation File to SimpleLocalize
        run: simplelocalize upload --apiKey=${{secrets.SIMPLELOCALIZE_API_KEY}} --uploadPath=./lang/en-US.json --uploadFormat=simplelocalize-json --languageKey=en-US
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v1.7.0
        with:
          title: Extracted translations into master
          labels: Auto PR
          branch: update-translations
          token: ${{secrets.GITHUB}}
